org: sp241930
app: server
# serverless.yml

service: server

custom: 
  secrets: ${file(secrets.json)}

provider:
  name: aws
  runtime: nodejs14.x
  stage: prod
  region: ap-south-1
  environment: # add environment property
    NODE_ENV: ${self:custom.secrets.NODE_ENV} 

functions:
  app:
    handler: app.server # reference the file and exported method
    events: # events trigger lambda functions
      - http: # this is an API Gateway HTTP event trigger
          path: /
          method: ANY
          cors: true
      - http: # all routes get proxied to the Express router
          path: /{proxy+}
          method: ANY
          cors: true